# Generated by Django 5.2.7 on 2025-11-23 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پروژه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوای کامل')),
                ('image', models.ImageField(blank=True, default='projects/default.jpg', null=True, upload_to='projects/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('in_progress', 'در حال توسعه'), ('on_hold', 'متوقف شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='لینک GitHub')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='لینک دمو')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='لینک وب\u200cسایت')),
                ('featured', models.BooleanField(default=False, verbose_name='پروژه ویژه')),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='projects', to='projects.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_date'],
            },
        ),
    ]
