# Generated by Django 5.2.8 on 2025-12-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterField(
            model_name="projects",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(
                blank=True,
                default="projects/default.jpg",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "تکمیل شده"),
                    ("in_progress", "در حال توسعه"),
                    ("on_hold", "متوقف شده"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
