# Generated by Django 5.2.8 on 2025-12-05 11:20

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projects_options_alter_projects_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="content",
            field=django_quill.fields.QuillField(default=""),
            preserve_default=False,
        ),
    ]
