# Generated by Django 5.2.8 on 2025-12-05 09:47

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(default=""),
            preserve_default=False,
        ),
    ]
