# Generated by Django 5.2.7 on 2025-11-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
